---
- name: >
    service/home-assistant
    : locals
    : Fill out user variables
  include_role:
    name: utils/podman/rootless/user
    tasks_from: locals
  vars:
    USER: "{{ home_assistant_service_user }}"


- name: >
    locals
    : Local variable structures
  set_fact:
    _hass_svc_user: "{{ _user }}"

    _hass_svc:
      name: home-assistant
      user: "{{ _user.name }}"
      home: "{{ _user.home }}"
      subdirs:
        - config
      role: service/home-assistant
      config_templates:
        - configuration.yaml:config/configuration.yaml
      description: Home Assistant
      #keep_uid: True
      network: host
      environment:
        TZ: "{{ time_zone }}"
      volumes:
        - host_path: "{{ _user.home }}/config"
          container_path: /config
          options: z
      image: ghcr.io/home-assistant/home-assistant:stable
