---
- name: >
    service/radicale
    : locals
    : Fill out user variables
  include_role:
    name: utils/podman/rootless/user
    tasks_from: locals
  vars:
    USER: "{{ radicale_service_user }}"


- name: >
    locals
    : Load client credentials
  include_vars:
    file: private/client-creds/radicale.yaml
    name: radicale_client_credentials
  run_once: True



- name: >
    locals
    : Service parameters
  set_fact:

    _radicale_svc_user: "{{ _user }}"

    _radicale_svc:
      name: radicale
      user: "{{ _user.name }}"
      home: "{{ _user.home }}"
      subdirs:
        - data
      description: Radicale DAV Server
      keep_uid: True
      #network: host
      read_only: True
      cap_drop: ["ALL"]
      cap_add: ["CHOWN", "SETUID", "SETGID", "KILL"]
      role: service/radicale
      config_templates:
        - config
      ports:
        - host_port: "{{ radicale_port }}"
          container_port: "{{ radicale_port }}"
      volumes:
        - host_path: "{{ _user.home }}/config"
          container_path: /config/config
          options: ro,z
        - host_path: "{{ _user.home }}/users.htpasswd"
          container_path: /users.htpasswd
          options: ro,z
        - host_path: "{{ _user.home }}/data"
          container_path: /data
          options: z
      health:
        cmd: curl --fail http://localhost:5232 || exit 1
        interval: 30s
        retries: 3
      extra_podman_args: >-
        --init
        --security-opt="no-new-privileges:true"
        --pids-limit 50
      #--memory 256M
      image: docker.io/tomsquest/docker-radicale
