---
- include_tasks: locals.yml
  when: not (_radicale_svc_user | default(''))


- name: >
    service/radicale
    : setup
    : Service user rootless setup
  include_role:
    name: utils/podman/rootless/user
    tasks_from: create
  vars:
    _user: "{{ _radicale_svc_user }}"


- name: >
    setup
    : Ensure python passlib for htpasswd management
  package:
    name: python3-passlib
  become: True

- name: >
    setup
    : Generate htpasswd file for auth
  htpasswd:
    path: "{{ _radicale_svc_user.home }}/users.htpasswd"
    crypt_scheme: apr_md5_crypt  # sha256_crypt
    name: "{{ item.name }}"
    password: "{{ item.pass }}"
    state: present
    mode: 0640
    owner: "{{ _radicale_svc_user.name }}"
    group: "{{ _radicale_svc_user.name }}"
  become: True
  loop: "{{ radicale_client_credentials.users }}"


- name: >
    service/radicale
    : setup
    : Setup radicale as rootless podman service
  include_role:
    name: utils/podman/rootless/service
    tasks_from: setup
  vars:
    SVC: "{{ _radicale_svc }}"
