---
- name: >
    utils/podman/rootless/user
    : create : {{ _user.name }}
    : Service user
  include_role:
    name: base/user
    tasks_from: create


- name: >
    create : {{ _user.name }}
    : Enable lingering
  command:
    cmd: loginctl enable-linger {{ _user.name }}
    creates: /var/lib/systemd/linger/{{ _user.name }}
  become: True


- name: >
    create : {{ _user.name }}
    : Ensure user systemd service directory
  file:
    path: "{{ _user.home }}/.config/systemd/user"
    state: directory
    mode: 0750
    owner: "{{ _user.name }}"
    group: "{{ _user.name }}"
  become: True


- name: >
    create : {{ _user.name }}
    : Enable podman autoupdate timer
  command:
    cmd: >-
      systemctl --user -M {{ _user.name }}@
      enable --now podman-auto-update.timer
    creates: "{{ _user.home }}/.config/systemd/user/timers.target.wants/podman-auto-update.timer"
  become: True
