---
- name: >
    utils/podman/rootless/user
    : locals : "{{ USER.name }}"
    : Set base user defaults
  include_role:
    name: base/user
    tasks_from: locals


- name: >
    locals
    : Set override variables
  set_fact:
    _rootless_user_override_vars:
      shell: /sbin/nologin


- name: >
    locals
    : Merge shell user variables
  set_fact:
    _user: "{{ _user | dict_update(_rootless_user_override_vars) }}"
