---
- name: >
    main
    : Script to generate nftables config
  copy:
    src: nftables-generate.sh
    dest: /usr/local/bin/nftables-generate.sh
    mode: 0755
  become: True
  notify: restart nftables-gen


- name: >
    main
    : Nftables-gen systemd service
  copy:
    src: nftables-gen.service
    dest: /etc/systemd/system/nftables-gen.service
    mode: 0644
  become: True
  notify: restart nftables-gen


- name: >
    main
    : Ensure chain config directories
  file:
    path: /etc/nftables/{{ item }}.d
    state: directory
    mode: 0700
  become: True
  loop:
    - prerouting
    - input
    - forward
    - output
    - nat-prerouting
    - nat-postrouting


- name: >
    main
    : Place default ssh rules to keep from breaking bootstrap run
  copy:
    src: default-ssh.conf
    dest: /etc/nftables/input.d/default-ssh.conf
    mode: 0600
  become: True
  when: allow_default_ssh
  notify: restart nftables-gen


- block:
  - name: >
      main
      : Tailscale service override directory
    file:
      path: /etc/systemd/system/tailscaled.service.d
      state: directory
      mode: 0755
    become: True

  - name: >
      main
      : Bind tailscale daemon to nftable-gen service
    copy:
      dest: /etc/systemd/system/tailscaled.service.d/override.conf
      content: |
        [Unit]
        BindsTo=nftables-gen.service
        Requires=nftables-gen.service
      mode: 0644
    become: True
  when: addresses.tailscale | default('')


- name: >
    base/nftables
    : main
    : Stop and disable firewalld firewall
  include_role:
    name: base/firewalld
    tasks_from: disable


- name: >
    main
    : Start and enable nftables-gen service
  systemd:
    name: nftables-gen
    state: started
    enabled: True
    daemon_reload: True
  become: True
