---
- name: >
    rule
    : Generate and place rule into appropriate config dir
  copy:
    content: >
      {%    if rule | default('')
      %}{{    rule
      }}{%  else
      %}{%    if interface | default('')
      %}{#      #}iifname {{ interface }} {#
      #}{%    endif
      %}{%    if port | default('')
      %}{#      #}ip protocol {{ protocol | default('tcp')
                }} th dport {{ port }} {#
      #}{%    endif
      %}{#    #}{{ policy | default('accept')
      }}{%    if comment | default('')
      %}{#      #} comment "{{ comment }}"{#
      #}{%    endif
      %}{%  endif %}
    dest: >-
      /etc/nftables/{{
          chain | default('input') | lower | replace('_', '-')
      }}.d/{{
          priority | default('')
      }}{{
          svc_name
      }}.conf
    mode: 0600
  become: True
  notify: restart nftables-gen
