---
USER:

  name: myuser
  home: /home/myuser
  uid: "2000"
  shell: /bin/bash

  pass_hash_name: myuser  # reference to private/pass-hashes/THIS, leave undefined to use locked password
  comment: ""

  sudo: False
  authorized_key_names: [] # reference to private/ssh-keys/THIS/public
