---
- name: >
    create : {{ _user.name }}
    : Create primary group with gid
  group:
    name: "{{ _user.name }}"
    gid: "{{ _user.uid }}"
    state: present
  become: True

- name: >
    create : {{ _user.name }}
    : Create user
  user:
    name: "{{ _user.name }}"
    home: "{{ _user.home }}"
    password: >-
        {%    if _user.pass_hash_name
        %}{{    lookup('file',
                  (ansible_config_file | dirname)
                  + '/private/pass-hashes/'
                  + _user.pass_hash_name
                )
        }}{%  else
                %}*{%
              endif
        %}
    group: "{{ _user.name }}"
    uid: "{{ _user.uid }}"
    shell: "{{ _user.shell }}"
    comment: "{{ _user.comment }}"
    state: present
  become: True

- name: >
    create : {{ _user.name }}
    : Add user to admin group
  user:
    name: "{{ _user.name }}"
    groups: ["{% 
        if ['fedora', 'centos', 'alpine', 'alma'] | group_match(group_names)
            %}wheel{%
        elif ['debian', 'ubuntu'] | group_match(group_names)
            %}sudo{%
        endif
      %}"]
    append: True
  become: True
  when: _user.sudo


- name: >
    base/user
    : create : {{ _user.name }}
    : Configure for sshd login
  include_role:
    name: service/sshd/user
  when: _user.authorized_key_names
