---
# This file is referenced by all other user
# creation roles
- name: >
    locals
    : Set user variables
  set_fact:
    _user:
      name: "{{ USER.name | default('myuser') }}"
      home: "{{ USER.home | default('/home/' + ( USER.name | default('myuser') )) }}"
      uid: >-
        {{ USER.uid | default(
            ((USER.name | md5 | int(0, 16) | string)[-4:] | int) + 1000
        ) }}
      shell: "{{ USER.shell | default('/bin/bash') }}"

      pass_hash_name: "{{ USER.pass_hash_name | default('') }}"
      comment: "{{ USER.comment | default('') }}"
      
      sudo: "{{ USER.sudo | default('') }}"
      authorized_key_names: "{{ USER.authorized_key_names | default([]) }}"
