---
- name: >
    main
    : Ensure mount dir exists
  file:
    path: "{{ item.dest }}"
    state: directory
  loop: "{{ mounts }}"
  become: True

- name: >
    main
    : Entries in fstab
  lineinfile:
    path: /etc/fstab
    line: >-
      {{ item.src }}
      {{ item.dest }}
      {{ item.type|default("ext4") }}
      {{ item.options|default("defaults") }}
      0 0
  loop: "{{ mounts }}"
  become: True

- name: >
    main
    : Run mount
  command: mount {{ item.dest }}
  loop: "{{ mounts }}"
  become: True
  register: out
  failed_when: >
    out.failed
    and "already mounted" not in out.stderr
  changed_when: >
    "already mounted" not in out.stderr
