---
- name: >
    config
    : SSHD config files
  template:
    src: "{{ item }}"
    dest: /etc/ssh/{{ item }}
    validate: /usr/sbin/sshd -t -f %s
  become: True
  loop:
    - sshd_config
    - sshd_algorithms
  notify: sshd restart


- include_tasks: selinux.yml
  when: >
    ['fedora', 'centos'] | group_match(group_names)


# - include_tasks: firewalld.yml
#   when: firewall == "firewalld"

- include_tasks: nftables.yml
  when: firewall == "nftables"
