---
- include_tasks: install.yml

- include_tasks: config.yml

- include_tasks: selinux.yml
  when: >
    ['fedora', 'centos'] | group_match(group_names)

- include_tasks: firewalld.yml
  when: firewall == "firewalld"
