---
- name: >
    service/sshd
    : nftables
    : Configure allow in nftables
  include_role:
    name: base/nftables
    tasks_from: rule
  vars:
    svc_name: sshd
    interface: tailscale0
    port: "{{ sshd_port }}"
    comment: "SSH over Tailscale"
