---
- name: >
    debian/setup
    : Install unattended-upgrades
  apt:
    name:
      - unattended-upgrades
    state: present
  become: True

- name: >
    debian/setup
    : Config for unattended upgrades
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    line: >-
      {{ item.opt }} {{ item.value }};
    regexp: >-
      .*{{ item.opt }} .*;
    state: present
  become: True
  loop:
    - opt: Unattended-Upgrade::MinimalSteps
      value: '"true"'
    - opt: Unattended-Upgrade::Automatic-Reboot
      value: '"true"'
    - opt: Unattended-Upgrade::Automatic-Reboot-Time
      value: '"06:00"'
  notify: restart unattended-upgrades

- name: >
    debian/setup
    : Start and enable service
  systemd:
    name: unattended-upgrades
    state: started
    enabled: True
  become: True


- name: >
    debian/main
    : Ensure cron.d directory
  file:
    path: /etc/cron.d
    state: directory
  become: True

- name: >
    debian/main
    : Periodic reboot cron job
  copy:
    dest: /etc/cron.d/kernel-reboot
    content: >
      {{ reboot_schedule }}
      root
      rpm -qa --last kernel
      | head -n1
      | grep $(uname -r)
      || shutdown -r now
  become: True
  when: periodic_reboot
