---
- include_role:
    name: shell/user
    tasks_from: locals


- name: >
    main : {{ _user.name }}
    : Config directory
  file:
    path: "{{ _user.home }}/.config/oh-my-zsh"
    state: directory
    owner: "{{ _user.name }}"
    group: "{{ _user.name }}"
  become: True


- name: >
    main : {{ _user.name }}
    : Customizations for oh-my-zsh
  copy:
    src: custom/
    dest: "{{ _user.home }}/.config/oh-my-zsh/"
    owner: "{{ _user.name }}"
    group: "{{ _user.name }}"
  become: True
  

- name: >
    main : {{ _user.name }}
    : Copy zshrc
  copy:
    src: zshrc
    dest: "{{ _user.home }}/.zshrc"
    owner: "{{ _user.name }}"
    group: "{{ _user.name }}"
    mode: 0600
  become: True
