---
- include_tasks: locals.yml
  when: not (_mosquitto_svc_user | default(''))


- name: >
    service/mosquitto
    : setup
    : Service user rootless setup
  include_role:
    name: utils/podman/rootless/user
    tasks_from: create
  vars:
    _user: "{{ _mosquitto_svc_user }}"


- name: >
    service/mosquitto
    : setup
    : Setup mosquitto as rootless podman service
  include_role:
    name: utils/podman/rootless/service
    tasks_from: setup
  vars:
    SVC: "{{ _mosquitto_svc }}"


- name: >
    service/mosquitto
    : setup
    : Setup mosquitto exporter as rootless podman service
  include_role:
    name: utils/podman/rootless/service
    tasks_from: setup
  vars:
    SVC: "{{ _mosquitto_exporter_svc }}"
