---
- name: >
    redhat/setup
    : Download and place tailscale rpm repo
  get_url:
    url: >-
      https://pkgs.tailscale.com/stable/{%
        if (['fedora'] | group_match(group_names))
          %}fedora{%
        elif (['centos'] | group_match(group_names))
          %}centos/{{ ansible_distribution_major_version }}{%
        elif (['rhel', 'alma', 'rocky'] | group_match(group_names))
          %}rhel/{{ ansible_distribution_major_version }}{%
        endif
      %}/tailscale.repo
    dest: /etc/yum.repos.d/tailscale.repo
    mode: 0644
  become: True


- name: >
    redhat/setup
    : Install tailscale
  dnf:
    name: tailscale
    state: present
  become: True
