---
- name: Common
  hosts: all
  tasks:

  # Redo bootstrap steps and post-bootstrap cleanup
    - name: SSHD
      include_role:
        name: service/sshd

    - name: System settings
      include_role:
        name: base/main

    - name: Enforce state for automation user
      include_role:
        name: base/user
      vars:
        USER: "{{ automation_user }}"

    - name: Remove init user
      include_role:
        name: init/user
        tasks_from: remove

  # Primary user and environment setup
    - name: Shell-based primary user setup
      include_role:
        name: shell/user
      vars:
        USER: "{{ primary_user }}"
      when: >
        ['server'] | group_match(group_names)



  # Self-hosted services
    - name: Load Service Map
      include_vars:
        file: private/maps/services.yaml
        name: services
      run_once: True

    - name: Prometheus Monitoring Server
      include_role:
        name: service/prometheus
      vars:
        monitored_services: "{{ services }}"
        prometheus_port: "{{ services | deep_get('prometheus.ports.primary', 9090) }}"
      when: inventory_hostname | has_service('prometheus', services)
