---
- include_role:
    name: shell/user
    tasks_from: locals


- name: >
    main : {{ _user.name }}
    : Ensure directories
  file:
    path: "{{ _user.home }}/.ssh/{{ item }}"
    state: directory
    owner: "{{ _user.name }}"
    group: "{{ _user.name }}"
    mode: 0700
  loop:
    - public
    - private
    - sockets
  become: True


- name: >
    main : {{ _user.name }}
    : Copy SSH private keys
  copy:
    content: >-
      {{ lookup('file',
          (ansible_config_file | dirname )
          + '/private/ssh-keys/'
          + item + '/private'
      ) }}
    dest: "{{ _user.home }}/.ssh/private/{{ item }}"
    owner: "{{ _user.name }}"
    group: "{{ _user.name }}"
    mode: 0600
  loop: "{{ _user.ssh_key_names }}"
  become: True


- name: >
    main : {{ _user.name }}
    : Copy corresponding SSH public keys
  copy:
    content: >-
      {{ lookup('file',
          (ansible_config_file | dirname )
          + '/private/ssh-keys/'
          + item + '/public'
      ) }}
    dest: "{{ _user.home }}/.ssh/public/{{ item }}"
    owner: "{{ _user.name }}"
    group: "{{ _user.name }}"
    mode: 0600
  loop: "{{ _user.ssh_key_names }}"
  become: True

# - name: >
#     main : {{ user.name }}
#     : SSH client config files
