---
- name: >
    service/caddy
    : locals
    : Fill out user variables
  include_role:
    name: utils/podman/rootless/user
    tasks_from: locals
  vars:
    USER: "{{ caddy_service_user }}"


- name: >
    locals
    : Local variable structures
  set_fact:

    _caddy_svc_user: "{{ _user }}"

    _caddy_svc:
      name: caddy
      user: "{{ _user.name }}"
      home: "{{ _user.home }}"
      subdirs:
        - conf
        - data
        - config
      role: service/caddy
      config_templates:
        - Caddyfile:conf/Caddyfile
      description: Caddy Reverse Proxy Server
      #keep_uid: True
      #network: host
      cap_add: ["NET_ADMIN"]
      read_only: True
      ports:
        - host_port: 8080
          container_port: 80
        - host_port: 8443
          container_port: 443
        - host_port: 8443
          container_port: 443
          protocol: udp
      volumes:
        - host_path: "{{ _user.home }}/conf"
          container_path: /etc/caddy
          options: ro,z
        - host_path: "{{ _user.home }}/data"
          container_path: /data
          options: rw,z
        - host_path: "{{ _user.home }}/config"
          container_path: /config
          options: ro,z
      image: docker.io/library/caddy:latest
