---
- name: >
    service/caddy
    : firewall : nftables
    : Port forward to unprivileged port
  include_role:
    name: base/nftables
    tasks_from: rule
  vars:
    chain: "{{ item.chain }}"
    svc_name: caddy
    rule: "{{ item.rule }}"
  loop:
    - chain: nat-prerouting
      rule: |
        tcp dport 80 redirect to :8080
        tcp dport 443 redirect to :8443
        udp dport 443 redirect to :8443

    - chain: input
      rule: |
        ip protocol tcp th dport 8080 accept comment "Caddy HTTP"
        ip protocol tcp th dport 8443 accept comment "Caddy HTTPS"
        ip protocol udp th dport 8443 accept comment "Caddy HTTPS UDP"
