---
- name: >
    setup : {{ SVC.name }}
    : Ensure specified subdirectories
  file:
    path: "{{ SVC.home }}/{{ item }}"
    state: directory
    mode: 0750
    owner: "{{ SVC.user }}"
    group: "{{ SVC.user }}"
  become: True
  loop: "{{ SVC.subdirs | default([]) }}"


- name: >
    setup : {{ SVC.name }}
    : Config files
  template:
    src: >-
      {{ ansible_config_file | dirname
      }}/roles/{{ SVC.role
      }}/templates/{{ (item | split(':'))[0] }}
    dest: >-
      {{ SVC.home }}/{{ (item | split(':'))[1] | default(item) }}
    mode: 0640
    owner: "{{ SVC.user }}"
    group: "{{ SVC.user }}"
  become: True
  loop: "{{ SVC.config_templates | default([]) }}"
  register: config_template


- name: >
    setup : {{ SVC.name }}
    : Create and enable systemd service
  include_tasks: "{{ item }}.yml"
  loop:
    - service-file
    - enable


- name: >
    setup : {{ SVC.name }}
    : Restart systemd service for changes
  include_tasks: restart.yml
  when: >
    systemd_service_file.changed
    or config_template.changed
