---
- name: >
    redhat/main
    : Install automatic update packages
  dnf:
    name:
      - dnf-automatic
    state: present
  become: True

- name: >
    redhat/main
    : Start and enable service
  systemd:
    name: dnf-automatic-install.timer
    state: started
    enabled: True
  become: True

- name: >
    redhat/main
    : Ensure cron.d directory
  file:
    path: /etc/cron.d
    state: directory
  become: True
  when: periodic_reboot

- name: >
    redhat/main
    : Periodic reboot cron job
  copy:
    dest: /etc/cron.d/kernel-reboot
    content: >
      {{ reboot_schedule }}
      root
      rpm -qa --last kernel
      | head -n1
      | grep $(uname -r)
      || shutdown -r now
  become: True
  when: periodic_reboot
