---
- include_tasks: locals.yml
  when: not (_caddy_svc_user | default(''))


- name: >
    service/caddy
    : setup
    : Service user rootless setup
  include_role:
    name: utils/podman/rootless/user
    tasks_from: create
  vars:
    _user: "{{ _caddy_svc_user }}"


- include_tasks: nftables.yml
  when: firewall == "nftables"


- name: >
    service/caddy
    : setup
    : Setup caddy as rootless podman service
  include_role:
    name: utils/podman/rootless/service
    tasks_from: setup
  vars:
    SVC: "{{ _caddy_svc }}"
