---
- include_role:
    name: base/user
    tasks_from: locals


- name: >
    main : {{ _user.name }}
    : Directories
  file:
    path: "{{ _user.home }}/.ssh"
    state: directory
    owner: "{{ _user.name }}"
    group: "{{ _user.name }}"
    mode: 0700
  become: True


- name: >
    main : {{ _user.name }}
    : Add to ssh group
  user:
    name: "{{ _user.name }}"
    groups:
      - "{{ sshd_allow_group }}"
    append: True
  become: True
  when: _user.authorized_key_names
 
- name: >
    main : {{ _user.name }}
    : Authorized Keys
  authorized_key:
    user: "{{ _user.name }}"
    state: present
    key: |
        {% for key_name in _user.authorized_key_names
        %}{{ lookup('file',
            (ansible_config_file | dirname)
            + '/private/ssh-keys/'
            + key_name
            + '/public'
        ) }}
        {% endfor %}
    exclusive: True
  become: True
