---
- include_tasks: locals.yml
  when: not (_prom_svc_user | default(''))


- name: >
    service/prometheus
    : setup
    : Service user rootless setup
  include_role:
    name: utils/podman/rootless/user
    tasks_from: create
  vars:
    _user: "{{ _prom_svc_user }}"


- name: >
    service/prometheus
    : setup
    : Setup prometheus as rootless podman service
  include_role:
    name: utils/podman/rootless/service
    tasks_from: setup
  vars:
    SVC: "{{ _prom_svc }}"
