---
- name: >
    main
    : Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - zsh
    - git
  become: True


- name: >
    main
    : Install common oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "/usr/local/etc/oh-my-zsh"
  become: True


- name: >
    main
    : Cron job to update oh-my-zsh weekly
  copy:
    src: oh-my-zsh_update.cron.sh
    dest: "/etc/cron.weekly/"
    mode: 0700
  become: True
