---
- name: >
    service/vikunja
    : locals
    : Fill out user variables
  include_role:
    name: utils/podman/rootless/user
    tasks_from: locals
  vars:
    USER: "{{ service_user }}"

- name: >
    locals
    : Local variable structures
  set_fact:

    _vikunja_svc_user: "{{ _user }}"

    _vikunja_svc:
      name: vikunja
      user: "{{ _user.name }}"
      home: "{{ _user.home }}"
      uid: "{{ _user.uid }}"
      keep_uid: True
      subdirs:
        - db
        - files
        - cache
      role: service/vikunja
      config_templates:
        - config.yaml
      description: "{{ description }}"
      ports:
        - host_port: "{{ ports.primary }}"
          container_port: 3456
      volumes:
        - host_path: "{{ _user.home }}/db"
          container_path: /db
          options: z
        - host_path: "{{ _user.home }}/files"
          container_path: /app/vikunja/files
          options: z
        - host_path: "{{ _user.home }}/cache"
          container_path: /app/vikunja/.cache
          options: z
        - host_path: "{{ _user.home }}/config.yaml"
          container_path: /etc/vikunja/config.yml
          options: ro,z
      image: docker.io/vikunja/vikunja:latest
