---
- include_tasks: locals.yml
  when: not (_vikunja_svc_user | default(''))


- name: >
    service/vikunja
    : setup
    : Service user rootless setup
  include_role:
    name: utils/podman/rootless/user
    tasks_from: create
  vars:
    _user: "{{ _vikunja_svc_user }}"


- name: >
    service/vikunja
    : setup
    : Setup vikunja as rootless podman service
  include_role:
    name: utils/podman/rootless/service
    tasks_from: setup
  vars:
    SVC: "{{ _vikunja_svc }}"
