---
- name: >
    service/audiobookshelf
    : locals
    : Fill out user variables
  include_role:
    name: utils/podman/rootless/user
    tasks_from: locals
  vars:
    USER: "{{ audiobookshelf_service_user }}"




- name: >
    locals
    : Service parameters
  set_fact:

    _audiobookshelf_svc_user: "{{ _user }}"

    _audiobookshelf_svc:
      name: audiobookshelf
      user: "{{ _user.name }}"
      home: "{{ _user.home }}"
      subdirs:
        - config
        - metadata
        - audiobooks
        - podcasts
      description: ABS Audiobook Server
      keep_uid: True
      #network: host
      read_only: True
      # role: service/audiobookshelf
      # config_templates:
      #   - config
      ports:
        - host_port: "{{ audiobookshelf_port }}"
          container_port: "{{ audiobookshelf_port }}"
      volumes:
        - host_path: "{{ _user.home }}/config"
          container_path: /config
        - host_path: "{{ _user.home }}/metadata"
          container_path: /metadata
        - host_path: "{{ _user.home }}/audiobooks"
          container_path: /audiobooks
        - host_path: "{{ _user.home }}/podcasts"
          container_path: /podcasts
      environment:
        - TZ=America/Los_Angeles
        - PORT={{ audiobookshelf_port }}

      image: ghcr.io/advplyr/audiobookshelf
