---
- include_tasks: locals.yml
  when: not (_audiobookshelf_svc_user | default(''))


- name: >
    service/audiobookshelf
    : setup
    : Service user rootless setup
  include_role:
    name: utils/podman/rootless/user
    tasks_from: create
  vars:
    _user: "{{ _audiobookshelf_svc_user }}"


- name: >
    service/audiobookshelf
    : setup
    : Setup audiobookshelf as rootless podman service
  include_role:
    name: utils/podman/rootless/service
    tasks_from: setup
  vars:
    SVC: "{{ _audiobookshelf_svc }}"
