---
- name: >
    selinux
    : Selinux allow listen on custom port
  community.general.seport:
    ports: "{{ sshd_port }}"
    proto: tcp
    setype: ssh_port_t
    state: present
  become: True
  when: sshd_port != 22
