---
- name: >
    init/cleanup
    : main
    : Remove init user
  include_role:
    name: init/user
    tasks_from: remove


- name: >
    main
    : Remove default ssh nftables rule
  file:
    path: /etc/nftables/input.d/default-ssh.conf
    state: absent
  become: True
  when: firewall == "nftables"
