---
USER:
  name: myuser
  home: /home/myuser
  uid: "2000"
  shell: /bin/bash
  pass_hash_name: myuser  # reference to private/pass-hashes/THIS
  comment: Myuser Lastname
  sudo: False
  authorized_key_names: [] # reference to private/ssh-keys/THIS/public
  ssh_key_names: [] # keys for user's ssh client, ref to private/ssh-keys/THIS/private
