---
http:
  server_host: "{{ addresses.tailscale.fqdn }}"

prometheus:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Default integrations
# https://www.home-assistant.io/integrations/default_config/
assist_pipeline:
backup:
bluetooth:
config:
conversation:
# dhcp:
energy:
# go2rtc:
history:
homeassistant_alerts:
cloud:
image_upload:
logbook:
media_source:
mobile_app:
my:
ssdp:
stream:
sun:
usb:
webhook:
zeroconf: