---
- include_tasks: redhat/setup.yml
  when: >
    ['fedora', 'centos', 'rhel', 'alma', 'rocky'] | group_match(group_names)

# - include_tasks: debian/setup.yml
#   when: >
#     ['debian', 'ubuntu'] | group_match(group_names)


- include_tasks: config.yml


- name: >
    main
    : Start and enable service
  systemd:
    name: tailscaled
    enabled: True
    state: started
  become: True
