---
- name: >
    install
    : SSHD installation
  package:
    name: openssh-server
    state: present
  become: True

- name: >
    install
    : SSHD Start on Boot
  service:
    name: sshd
    enabled: "{{ sshd_enabled }}"
  become: True

- name: >
    install
    : Create /run/sshd
  file:
    state: directory
    path: /run/sshd
  become: True

- name: >
    install
    : Ensure SSHable group
  group:
    name: "{{ sshd_allow_group }}"
  become: True
