---
- include_tasks: locals.yml
  when: not (_hass_svc_user | default(''))


- name: >
    service/home-assistant
    : setup
    : Service user rootless setup
  include_role:
    name: utils/podman/rootless/user
    tasks_from: create
  vars:
    _user: "{{ _hass_svc_user }}"


- name: >
    service/home-assistant
    : setup
    : Setup home-assistant as rootless podman service
  include_role:
    name: utils/podman/rootless/service
    tasks_from: setup
  vars:
    SVC: "{{ _hass_svc }}"
