---
- name: >
    config
    : Ensure config directory
  file:
    path: /var/lib/tailscale
    state: directory
    mode: 0700
  become: True


- name: >
    config
    : Place tailscale node state file
  copy:
    src: private/tailscale/{{ inventory_hostname }}.state
    dest: /var/lib/tailscale/tailscaled.state
    mode: 0600
  become: True
  notify: restart tailscaled
