---
- include_role:
    name: base/update

- include_role:
    name: base/auto-updates

- include_role:
    name: base/hostname

- include_role:
    name: base/locale

- include_role:
    name: base/timezone

- include_role:
    name: base/mounts

- include_role:
    name: base/selinux
  when: >
    ['fedora', 'centos'] | group_match(group_names)


- include_role:
    name: base/firewalld
    tasks_from: remove
  when: firewall != "firewalld"

- include_role:
    name: base/nftables
  when: firewall == "nftables"



- name: >
    main
    : Check for node tailscale config
  stat:
    path: private/tailscale/{{ inventory_hostname }}.state
  become: True
  delegate_to: localhost
  register: tailscale_config

- include_role:
    name: base/tailscale
  when: tailscale_config.stat.exists
