---
- name: Remove temporary user
  user:
    name: "{{ bootstrap_user_name }}"
    state: absent
  become: True
  when: bootstrap_user_name != "root"

- name: Remove temporary user home
  file:
    path: "/home/{{ bootstrap_user_name }}"
    state: absent
  become: True
  when: bootstrap_user_name != "root"
