---
- name: >
    enable : {{ SVC.name }}
    : Enable service
  command:
    cmd: >-
      systemctl --user -M {{ SVC.user }}@
      enable {{ SVC.name }}
    creates: >-
      {{
        SVC.home
      }}/.config/systemd/user/default.target.wants/{{
        SVC.name
      }}.service
  become: True
