---
- name: >
    service-file : {{ SVC.name }}
    : User systemd service file
  template:
    src: rootless.service
    dest: >-
      {{ 
        SVC.home
      }}/.config/systemd/user/{{
         SVC.name
      }}.service
    mode: 0640
    owner: "{{ SVC.user }}"
    group: "{{ SVC.user }}"
  become: True
  register: systemd_service_file


- name: >
    service-file : {{ SVC.name }}
    : Systemd user daemon reload
  command:
    cmd: >
      systemctl --user -M {{ SVC.user }}@
      daemon-reload
  become: True
  when: systemd_service_file.changed
